// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clubMessage.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Request15001_Params;
@class Request15002_Params;
@class RequestCommon;
@class Response15001_Data;
@class Response15002_Data;
@class ResponseCommon;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ClubMessageRoot

@interface ClubMessageRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Request15001

typedef GPB_ENUM(Request15001_FieldNumber) {
  Request15001_FieldNumber_Common = 1,
  Request15001_FieldNumber_Params = 2,
};

//获取用户消息列表
//url: /messageAction/getMessages
@interface Request15001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request15001_Params *params;

@end

#pragma mark - Request15001_Params

typedef GPB_ENUM(Request15001_Params_FieldNumber) {
  Request15001_Params_FieldNumber_Readed = 1,
};

@interface Request15001_Params : GPBMessage

// 0 获取全部（可不传该参数表示获取全部） 
@property(nonatomic, readwrite) int32_t readed;

@end

#pragma mark - Response15001

typedef GPB_ENUM(Response15001_FieldNumber) {
  Response15001_FieldNumber_Common = 1,
  Response15001_FieldNumber_Data_p = 2,
};

@interface Response15001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response15001_Data *data_p;

@end

#pragma mark - Response15001_Data

typedef GPB_ENUM(Response15001_Data_FieldNumber) {
  Response15001_Data_FieldNumber_MessagesArray = 1,
};

@interface Response15001_Data : GPBMessage

//消息列表
// |messagesArray| contains |Message|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *messagesArray;
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

@end

#pragma mark - Request15002

typedef GPB_ENUM(Request15002_FieldNumber) {
  Request15002_FieldNumber_Common = 1,
  Request15002_FieldNumber_Params = 2,
};

//读消息 用户点击该条消息，需要把该消息设置为已读
//url: /messageAction/readMessage
@interface Request15002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request15002_Params *params;

@end

#pragma mark - Request15002_Params

typedef GPB_ENUM(Request15002_Params_FieldNumber) {
  Request15002_Params_FieldNumber_MessageId = 1,
};

@interface Request15002_Params : GPBMessage

//该消息的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@end

#pragma mark - Response15002

typedef GPB_ENUM(Response15002_FieldNumber) {
  Response15002_FieldNumber_Common = 1,
  Response15002_FieldNumber_Data_p = 2,
};

@interface Response15002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response15002_Data *data_p;

@end

#pragma mark - Response15002_Data

@interface Response15002_Data : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
