// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rongyun.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Request16005_Params;
@class Request16006_Params;
@class Request16007_Params;
@class Request16008_Params;
@class Request16009_Params;
@class RequestCommon;
@class Response16005_Data;
@class Response16006_Data;
@class Response16007_Data;
@class Response16008_Data;
@class Response16009_Data;
@class ResponseCommon;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RongyunRoot

@interface RongyunRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Request16005

typedef GPB_ENUM(Request16005_FieldNumber) {
  Request16005_FieldNumber_Common = 1,
  Request16005_FieldNumber_Params = 2,
};

// 加入、退出 聊天小组
//url: /rongyunAction/joinTalkTeam
@interface Request16005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request16005_Params *params;

@end

#pragma mark - Request16005_Params

typedef GPB_ENUM(Request16005_Params_FieldNumber) {
  Request16005_Params_FieldNumber_UserId = 1,
  Request16005_Params_FieldNumber_TalkTeamId = 2,
  Request16005_Params_FieldNumber_Action = 3,
  Request16005_Params_FieldNumber_TalkTeamName = 4,
};

@interface Request16005_Params : GPBMessage

//要加入聊天小组的人的userid
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

//要加入的聊天小组的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamId;

// 1：加入 or 2：退出
@property(nonatomic, readwrite) int32_t action;

//聊天小组的名字
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamName;

@end

#pragma mark - Response16005

typedef GPB_ENUM(Response16005_FieldNumber) {
  Response16005_FieldNumber_Common = 1,
  Response16005_FieldNumber_Data_p = 2,
};

@interface Response16005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response16005_Data *data_p;

@end

#pragma mark - Response16005_Data

typedef GPB_ENUM(Response16005_Data_FieldNumber) {
  Response16005_Data_FieldNumber_MessagesArray = 1,
};

@interface Response16005_Data : GPBMessage

//消息列表
// |messagesArray| contains |Message|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *messagesArray;
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

@end

#pragma mark - Request16006

typedef GPB_ENUM(Request16006_FieldNumber) {
  Request16006_FieldNumber_Common = 1,
  Request16006_FieldNumber_Params = 2,
};

// 解散群组
//url: /rongyunAction/dismissTalkTeam
@interface Request16006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request16006_Params *params;

@end

#pragma mark - Request16006_Params

typedef GPB_ENUM(Request16006_Params_FieldNumber) {
  Request16006_Params_FieldNumber_TalkTeamId = 1,
};

@interface Request16006_Params : GPBMessage

//要解散的小组的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamId;

@end

#pragma mark - Response16006

typedef GPB_ENUM(Response16006_FieldNumber) {
  Response16006_FieldNumber_Common = 1,
  Response16006_FieldNumber_Data_p = 2,
};

@interface Response16006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response16006_Data *data_p;

@end

#pragma mark - Response16006_Data

@interface Response16006_Data : GPBMessage

@end

#pragma mark - Request16007

typedef GPB_ENUM(Request16007_FieldNumber) {
  Request16007_FieldNumber_Common = 1,
  Request16007_FieldNumber_Params = 2,
};

// 刷新群组信息：更改群组名称
//url: /rongyunAction/refreshTalkTeam
@interface Request16007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request16007_Params *params;

@end

#pragma mark - Request16007_Params

typedef GPB_ENUM(Request16007_Params_FieldNumber) {
  Request16007_Params_FieldNumber_TalkTeamId = 1,
  Request16007_Params_FieldNumber_TalkTeamName = 2,
};

@interface Request16007_Params : GPBMessage

//要刷新的小组的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamId;

//要更改的名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamName;

@end

#pragma mark - Response16007

typedef GPB_ENUM(Response16007_FieldNumber) {
  Response16007_FieldNumber_Common = 1,
  Response16007_FieldNumber_Data_p = 2,
};

@interface Response16007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response16007_Data *data_p;

@end

#pragma mark - Response16007_Data

@interface Response16007_Data : GPBMessage

@end

#pragma mark - Request16008

typedef GPB_ENUM(Request16008_FieldNumber) {
  Request16008_FieldNumber_Common = 1,
  Request16008_FieldNumber_Params = 2,
};

// 获取聊天小组详情
//url: /rongyunAction/getTalkTeamInfo
@interface Request16008 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request16008_Params *params;

@end

#pragma mark - Request16008_Params

typedef GPB_ENUM(Request16008_Params_FieldNumber) {
  Request16008_Params_FieldNumber_TalkTeamId = 1,
};

@interface Request16008_Params : GPBMessage

//要获取的小组的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamId;

@end

#pragma mark - Response16008

typedef GPB_ENUM(Response16008_FieldNumber) {
  Response16008_FieldNumber_Common = 1,
  Response16008_FieldNumber_Data_p = 2,
};

@interface Response16008 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response16008_Data *data_p;

@end

#pragma mark - Response16008_Data

typedef GPB_ENUM(Response16008_Data_FieldNumber) {
  Response16008_Data_FieldNumber_TalkTeamId = 1,
  Response16008_Data_FieldNumber_TalkTeamName = 2,
  Response16008_Data_FieldNumber_TalkTeamAvatarURL = 3,
};

@interface Response16008_Data : GPBMessage

//要获取的小组的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamId;

//小组名
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamName;

// 聊天小组头像url
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamAvatarURL;

@end

#pragma mark - Request16009

typedef GPB_ENUM(Request16009_FieldNumber) {
  Request16009_FieldNumber_Common = 1,
  Request16009_FieldNumber_Params = 2,
};

// 获取用户所在聊天小组信息
//url: /rongyunAction/getUserTalkTeamInfo
@interface Request16009 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request16009_Params *params;

@end

#pragma mark - Request16009_Params

@interface Request16009_Params : GPBMessage

@end

#pragma mark - Response16009

typedef GPB_ENUM(Response16009_FieldNumber) {
  Response16009_FieldNumber_Common = 1,
  Response16009_FieldNumber_Data_p = 2,
};

@interface Response16009 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response16009_Data *data_p;

@end

#pragma mark - Response16009_Data

typedef GPB_ENUM(Response16009_Data_FieldNumber) {
  Response16009_Data_FieldNumber_TeaminfosArray = 1,
};

@interface Response16009_Data : GPBMessage

// |teaminfosArray| contains |TeamInfo|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *teaminfosArray;
@property(nonatomic, readonly) NSUInteger teaminfosArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
