// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clubVclub.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class ClubDetail;
@class Request11000_Params;
@class Request11001_Params;
@class Request11002_Params;
@class Request11003_Params;
@class Request11004_Params;
@class Request11005_Params;
@class Request11006_Params;
@class Request11007_Params;
@class Request11008_Params;
@class Request11009_Params;
@class Request11010_Params;
@class Request11011_Params;
@class Request11012_Params;
@class Request11013_Params;
@class Request11014_Params;
@class Request11015_Params;
@class Request11016_Params;
@class Request11017_Params;
@class Request11018_Params;
@class RequestCommon;
@class Response11000_Data;
@class Response11001_Data;
@class Response11002_Data;
@class Response11003_Data;
@class Response11004_Data;
@class Response11005_Data;
@class Response11006_Data;
@class Response11007_Data;
@class Response11008_Data;
@class Response11009_Data;
@class Response11010_Data;
@class Response11011_Data;
@class Response11012_Data;
@class Response11013_Data;
@class Response11014_Data;
@class Response11015_Data;
@class Response11016_Data;
@class Response11017_Data;
@class Response11018_Data;
@class ResponseCommon;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ClubVclubRoot

@interface ClubVclubRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Request11000

typedef GPB_ENUM(Request11000_FieldNumber) {
  Request11000_FieldNumber_Common = 1,
  Request11000_FieldNumber_Params = 2,
};

//录入酒吧     for h5
//url: /clubAction/insertClub
@interface Request11000 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11000_Params *params;

@end

#pragma mark - Request11000_Params

typedef GPB_ENUM(Request11000_Params_FieldNumber) {
  Request11000_Params_FieldNumber_ClubName = 1,
  Request11000_Params_FieldNumber_ClubDescription = 2,
  Request11000_Params_FieldNumber_ClubCover = 3,
  Request11000_Params_FieldNumber_ClubLocation = 4,
  Request11000_Params_FieldNumber_ClubPhone = 5,
  Request11000_Params_FieldNumber_ClubAvatar = 6,
};

@interface Request11000_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubName;

//酒吧简介
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubDescription;

//酒吧cover图
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubCover;

//酒吧位置
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubLocation;

//酒吧电话
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubPhone;

//酒吧头像
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubAvatar;

@end

#pragma mark - Response11000

typedef GPB_ENUM(Response11000_FieldNumber) {
  Response11000_FieldNumber_Common = 1,
  Response11000_FieldNumber_Data_p = 2,
};

@interface Response11000 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11000_Data *data_p;

@end

#pragma mark - Response11000_Data

@interface Response11000_Data : GPBMessage

@end

#pragma mark - Request11001

typedef GPB_ENUM(Request11001_FieldNumber) {
  Request11001_FieldNumber_Common = 1,
  Request11001_FieldNumber_Params = 2,
};

//获取酒吧列表  11001
//url: /clubAction/getClubs
@interface Request11001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11001_Params *params;

@end

#pragma mark - Request11001_Params

typedef GPB_ENUM(Request11001_Params_FieldNumber) {
  Request11001_Params_FieldNumber_Order = 1,
  Request11001_Params_FieldNumber_Latitude = 2,
  Request11001_Params_FieldNumber_Longitude = 3,
  Request11001_Params_FieldNumber_LastClubId = 4,
};

@interface Request11001_Params : GPBMessage

//酒吧排序方法     1：离我最近 2：人气最高 3：消费最高
@property(nonatomic, readwrite) int32_t order;

//可选  纬度
@property(nonatomic, readwrite) float latitude;

//可选  经度
@property(nonatomic, readwrite) float longitude;

//可选，上一页最后一个id
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastClubId;

@end

#pragma mark - Response11001

typedef GPB_ENUM(Response11001_FieldNumber) {
  Response11001_FieldNumber_Common = 1,
  Response11001_FieldNumber_Data_p = 2,
};

@interface Response11001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11001_Data *data_p;

@end

#pragma mark - Response11001_Data

typedef GPB_ENUM(Response11001_Data_FieldNumber) {
  Response11001_Data_FieldNumber_ClubsArray = 1,
};

@interface Response11001_Data : GPBMessage

//酒吧数组
// |clubsArray| contains |BriefClub|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *clubsArray;
@property(nonatomic, readonly) NSUInteger clubsArray_Count;

@end

#pragma mark - Request11002

typedef GPB_ENUM(Request11002_FieldNumber) {
  Request11002_FieldNumber_Common = 1,
  Request11002_FieldNumber_Params = 2,
};

//酒吧签到 11002
//url: /clubActin/signUp
@interface Request11002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11002_Params *params;

@end

#pragma mark - Request11002_Params

typedef GPB_ENUM(Request11002_Params_FieldNumber) {
  Request11002_Params_FieldNumber_ClubId = 1,
};

@interface Request11002_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

@end

#pragma mark - Response11002

typedef GPB_ENUM(Response11002_FieldNumber) {
  Response11002_FieldNumber_Common = 1,
  Response11002_FieldNumber_Data_p = 2,
};

@interface Response11002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11002_Data *data_p;

@end

#pragma mark - Response11002_Data

@interface Response11002_Data : GPBMessage

@end

#pragma mark - Request11003

typedef GPB_ENUM(Request11003_FieldNumber) {
  Request11003_FieldNumber_Common = 1,
  Request11003_FieldNumber_Params = 2,
};

//酒吧签到之获取签到情况 11003
//url: /clubActin/signUpState
@interface Request11003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11003_Params *params;

@end

#pragma mark - Request11003_Params

typedef GPB_ENUM(Request11003_Params_FieldNumber) {
  Request11003_Params_FieldNumber_ClubId = 1,
};

@interface Request11003_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

@end

#pragma mark - Response11003

typedef GPB_ENUM(Response11003_FieldNumber) {
  Response11003_FieldNumber_Common = 1,
  Response11003_FieldNumber_Data_p = 2,
};

@interface Response11003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11003_Data *data_p;

@end

#pragma mark - Response11003_Data

typedef GPB_ENUM(Response11003_Data_FieldNumber) {
  Response11003_Data_FieldNumber_State = 1,
};

@interface Response11003_Data : GPBMessage

// 1已经签到  2：未签到
@property(nonatomic, readwrite) int32_t state;

@end

#pragma mark - Request11004

typedef GPB_ENUM(Request11004_FieldNumber) {
  Request11004_FieldNumber_Common = 1,
  Request11004_FieldNumber_Params = 2,
};

//获取聊天室成员 11004
//url: /clubAction/getChatroomMember
@interface Request11004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11004_Params *params;

@end

#pragma mark - Request11004_Params

typedef GPB_ENUM(Request11004_Params_FieldNumber) {
  Request11004_Params_FieldNumber_ClubId = 1,
};

@interface Request11004_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

@end

#pragma mark - Response11004

typedef GPB_ENUM(Response11004_FieldNumber) {
  Response11004_FieldNumber_Common = 1,
  Response11004_FieldNumber_Data_p = 2,
};

@interface Response11004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11004_Data *data_p;

@end

#pragma mark - Response11004_Data

typedef GPB_ENUM(Response11004_Data_FieldNumber) {
  Response11004_Data_FieldNumber_ChatUsersArray = 1,
};

@interface Response11004_Data : GPBMessage

//聊天成员简要信息
// |chatUsersArray| contains |ChatUser|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *chatUsersArray;
@property(nonatomic, readonly) NSUInteger chatUsersArray_Count;

@end

#pragma mark - Request11005

typedef GPB_ENUM(Request11005_FieldNumber) {
  Request11005_FieldNumber_Common = 1,
  Request11005_FieldNumber_Params = 2,
};

//搜索聊天室成员 11005
//url: /clubAction/searchChatroomMember
@interface Request11005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11005_Params *params;

@end

#pragma mark - Request11005_Params

typedef GPB_ENUM(Request11005_Params_FieldNumber) {
  Request11005_Params_FieldNumber_ClubId = 1,
  Request11005_Params_FieldNumber_Keyword = 2,
};

@interface Request11005_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

//搜索关键词
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

@end

#pragma mark - Response11005

typedef GPB_ENUM(Response11005_FieldNumber) {
  Response11005_FieldNumber_Common = 1,
  Response11005_FieldNumber_Data_p = 2,
};

@interface Response11005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11005_Data *data_p;

@end

#pragma mark - Response11005_Data

typedef GPB_ENUM(Response11005_Data_FieldNumber) {
  Response11005_Data_FieldNumber_ChatUsersArray = 1,
};

@interface Response11005_Data : GPBMessage

//聊天成员简要信息
// |chatUsersArray| contains |ChatUser|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *chatUsersArray;
@property(nonatomic, readonly) NSUInteger chatUsersArray_Count;

@end

#pragma mark - Request11006

typedef GPB_ENUM(Request11006_FieldNumber) {
  Request11006_FieldNumber_Common = 1,
  Request11006_FieldNumber_Params = 2,
};

//创建聊天小组 11006
//url: /clubAction/createChatTeam
@interface Request11006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11006_Params *params;

@end

#pragma mark - Request11006_Params

typedef GPB_ENUM(Request11006_Params_FieldNumber) {
  Request11006_Params_FieldNumber_ClubId = 1,
  Request11006_Params_FieldNumber_UseridsArray = 2,
};

@interface Request11006_Params : GPBMessage

//可选  如果是从酒吧创建的，就加上该字段
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

//小组成员的id s
// |useridsArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *useridsArray;
@property(nonatomic, readonly) NSUInteger useridsArray_Count;

@end

#pragma mark - Response11006

typedef GPB_ENUM(Response11006_FieldNumber) {
  Response11006_FieldNumber_Common = 1,
  Response11006_FieldNumber_Data_p = 2,
};

@interface Response11006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11006_Data *data_p;

@end

#pragma mark - Response11006_Data

typedef GPB_ENUM(Response11006_Data_FieldNumber) {
  Response11006_Data_FieldNumber_TargetDiscussionId = 2,
  Response11006_Data_FieldNumber_Title = 3,
};

@interface Response11006_Data : GPBMessage

//聊天小组的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetDiscussionId;

//聊天标题， 默认是小组名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@end

#pragma mark - Request11007

typedef GPB_ENUM(Request11007_FieldNumber) {
  Request11007_FieldNumber_Common = 1,
  Request11007_FieldNumber_Params = 2,
};

//获取酒吧详情 11007
//url: /clubAction/getClubDetail
@interface Request11007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11007_Params *params;

@end

#pragma mark - Request11007_Params

typedef GPB_ENUM(Request11007_Params_FieldNumber) {
  Request11007_Params_FieldNumber_ClubId = 1,
};

@interface Request11007_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

@end

#pragma mark - Response11007

typedef GPB_ENUM(Response11007_FieldNumber) {
  Response11007_FieldNumber_Common = 1,
  Response11007_FieldNumber_Data_p = 2,
};

@interface Response11007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11007_Data *data_p;

@end

#pragma mark - Response11007_Data

typedef GPB_ENUM(Response11007_Data_FieldNumber) {
  Response11007_Data_FieldNumber_Club = 1,
};

@interface Response11007_Data : GPBMessage

@property(nonatomic, readwrite) BOOL hasClub;
@property(nonatomic, readwrite, strong, null_resettable) ClubDetail *club;

@end

#pragma mark - Request11008

typedef GPB_ENUM(Request11008_FieldNumber) {
  Request11008_FieldNumber_Common = 1,
  Request11008_FieldNumber_Params = 2,
};

//获取酒吧livephoto 11008
//url: /clubAction/getClubLivePhoto
@interface Request11008 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11008_Params *params;

@end

#pragma mark - Request11008_Params

typedef GPB_ENUM(Request11008_Params_FieldNumber) {
  Request11008_Params_FieldNumber_ClubId = 1,
  Request11008_Params_FieldNumber_LastLivePhotoId = 2,
};

@interface Request11008_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

//可选，上一页最后一个livephoto id
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastLivePhotoId;

@end

#pragma mark - Response11008

typedef GPB_ENUM(Response11008_FieldNumber) {
  Response11008_FieldNumber_Common = 1,
  Response11008_FieldNumber_Data_p = 2,
};

@interface Response11008 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11008_Data *data_p;

@end

#pragma mark - Response11008_Data

typedef GPB_ENUM(Response11008_Data_FieldNumber) {
  Response11008_Data_FieldNumber_LivePhotosArray = 2,
};

@interface Response11008_Data : GPBMessage

// |livePhotosArray| contains |LivePhoto|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *livePhotosArray;
@property(nonatomic, readonly) NSUInteger livePhotosArray_Count;

@end

#pragma mark - Request11009

typedef GPB_ENUM(Request11009_FieldNumber) {
  Request11009_FieldNumber_Common = 1,
  Request11009_FieldNumber_Params = 2,
};

//酒吧点赞 取消点赞 11009
//url: /clubAction/likeClub
@interface Request11009 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11009_Params *params;

@end

#pragma mark - Request11009_Params

typedef GPB_ENUM(Request11009_Params_FieldNumber) {
  Request11009_Params_FieldNumber_ClubId = 1,
  Request11009_Params_FieldNumber_Flag = 2,
};

@interface Request11009_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

//1 点赞  2取消点赞
@property(nonatomic, readwrite) int32_t flag;

@end

#pragma mark - Response11009

typedef GPB_ENUM(Response11009_FieldNumber) {
  Response11009_FieldNumber_Common = 1,
  Response11009_FieldNumber_Data_p = 2,
};

@interface Response11009 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11009_Data *data_p;

@end

#pragma mark - Response11009_Data

@interface Response11009_Data : GPBMessage

@end

#pragma mark - Request11010

typedef GPB_ENUM(Request11010_FieldNumber) {
  Request11010_FieldNumber_Common = 1,
  Request11010_FieldNumber_Params = 2,
};

//酒吧livephoto点赞 11010
//url: /clubAction/likeClubLivePhoto
@interface Request11010 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11010_Params *params;

@end

#pragma mark - Request11010_Params

typedef GPB_ENUM(Request11010_Params_FieldNumber) {
  Request11010_Params_FieldNumber_LivePhotoId = 1,
  Request11010_Params_FieldNumber_Flag = 2,
};

@interface Request11010_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *livePhotoId;

//1 点赞   2取消点赞
@property(nonatomic, readwrite) int32_t flag;

@end

#pragma mark - Response11010

typedef GPB_ENUM(Response11010_FieldNumber) {
  Response11010_FieldNumber_Common = 1,
  Response11010_FieldNumber_Data_p = 2,
};

@interface Response11010 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11010_Data *data_p;

@end

#pragma mark - Response11010_Data

@interface Response11010_Data : GPBMessage

@end

#pragma mark - Request11011

typedef GPB_ENUM(Request11011_FieldNumber) {
  Request11011_FieldNumber_Common = 1,
  Request11011_FieldNumber_Params = 2,
};

//修改酒吧聊天昵称 11011
//url: /clubAction/changeChatroomUsername
@interface Request11011 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11011_Params *params;

@end

#pragma mark - Request11011_Params

typedef GPB_ENUM(Request11011_Params_FieldNumber) {
  Request11011_Params_FieldNumber_ChatroomId = 1,
  Request11011_Params_FieldNumber_Username = 2,
};

@interface Request11011_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatroomId;

//要显示的聊天昵称
@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@end

#pragma mark - Response11011

typedef GPB_ENUM(Response11011_FieldNumber) {
  Response11011_FieldNumber_Common = 1,
  Response11011_FieldNumber_Data_p = 2,
};

@interface Response11011 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11011_Data *data_p;

@end

#pragma mark - Response11011_Data

@interface Response11011_Data : GPBMessage

@end

#pragma mark - Request11012

typedef GPB_ENUM(Request11012_FieldNumber) {
  Request11012_FieldNumber_Common = 1,
  Request11012_FieldNumber_Params = 2,
};

//设置聊天背景 11012
//url: /clubAction/changeChatroomBackground
@interface Request11012 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11012_Params *params;

@end

#pragma mark - Request11012_Params

typedef GPB_ENUM(Request11012_Params_FieldNumber) {
  Request11012_Params_FieldNumber_ChatroomId = 1,
  Request11012_Params_FieldNumber_BackgroundURL = 2,
};

@interface Request11012_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatroomId;

//要显示的聊天背景
@property(nonatomic, readwrite, copy, null_resettable) NSString *backgroundURL;

@end

#pragma mark - Response11012

typedef GPB_ENUM(Response11012_FieldNumber) {
  Response11012_FieldNumber_Common = 1,
  Response11012_FieldNumber_Data_p = 2,
};

@interface Response11012 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11012_Data *data_p;

@end

#pragma mark - Response11012_Data

@interface Response11012_Data : GPBMessage

@end

#pragma mark - Request11013

typedef GPB_ENUM(Request11013_FieldNumber) {
  Request11013_FieldNumber_Common = 1,
  Request11013_FieldNumber_Params = 2,
};

//添加livephoto 11013
//url: /clubAction/addLivePhoto
@interface Request11013 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11013_Params *params;

@end

#pragma mark - Request11013_Params

typedef GPB_ENUM(Request11013_Params_FieldNumber) {
  Request11013_Params_FieldNumber_ClubId = 1,
  Request11013_Params_FieldNumber_LivePhotoURL = 3,
};

@interface Request11013_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

//上传上七牛的key
@property(nonatomic, readwrite, copy, null_resettable) NSString *livePhotoURL;

@end

#pragma mark - Response11013

typedef GPB_ENUM(Response11013_FieldNumber) {
  Response11013_FieldNumber_Common = 1,
  Response11013_FieldNumber_Data_p = 2,
};

@interface Response11013 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11013_Data *data_p;

@end

#pragma mark - Response11013_Data

@interface Response11013_Data : GPBMessage

@end

#pragma mark - Request11014

typedef GPB_ENUM(Request11014_FieldNumber) {
  Request11014_FieldNumber_Common = 1,
  Request11014_FieldNumber_Params = 2,
};

//获取用户聊天token 11014
//url: /clubAction/getRongyunToken
@interface Request11014 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11014_Params *params;

@end

#pragma mark - Request11014_Params

@interface Request11014_Params : GPBMessage

@end

#pragma mark - Response11014

typedef GPB_ENUM(Response11014_FieldNumber) {
  Response11014_FieldNumber_Common = 1,
  Response11014_FieldNumber_Data_p = 2,
};

@interface Response11014 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11014_Data *data_p;

@end

#pragma mark - Response11014_Data

typedef GPB_ENUM(Response11014_Data_FieldNumber) {
  Response11014_Data_FieldNumber_Token = 2,
};

@interface Response11014_Data : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - Request11015

typedef GPB_ENUM(Request11015_FieldNumber) {
  Request11015_FieldNumber_Common = 1,
  Request11015_FieldNumber_Params = 2,
};

//获取用户七牛上传图片Token 11015
//url: /clubAction/getQiniuToken
@interface Request11015 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11015_Params *params;

@end

#pragma mark - Request11015_Params

@interface Request11015_Params : GPBMessage

@end

#pragma mark - Response11015

typedef GPB_ENUM(Response11015_FieldNumber) {
  Response11015_FieldNumber_Common = 1,
  Response11015_FieldNumber_Data_p = 2,
};

@interface Response11015 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11015_Data *data_p;

@end

#pragma mark - Response11015_Data

typedef GPB_ENUM(Response11015_Data_FieldNumber) {
  Response11015_Data_FieldNumber_Token = 2,
};

@interface Response11015_Data : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - Request11016

typedef GPB_ENUM(Request11016_FieldNumber) {
  Request11016_FieldNumber_Common = 1,
  Request11016_FieldNumber_Params = 2,
};

//加入酒吧聊天室   11016
//url: /clubAction/addToTalkRoom
@interface Request11016 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11016_Params *params;

@end

#pragma mark - Request11016_Params

typedef GPB_ENUM(Request11016_Params_FieldNumber) {
  Request11016_Params_FieldNumber_Clubid = 1,
};

@interface Request11016_Params : GPBMessage

//酒吧 也即是酒吧聊天室id
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubid;

@end

#pragma mark - Response11016

typedef GPB_ENUM(Response11016_FieldNumber) {
  Response11016_FieldNumber_Common = 1,
  Response11016_FieldNumber_Data_p = 2,
};

@interface Response11016 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11016_Data *data_p;

@end

#pragma mark - Response11016_Data

@interface Response11016_Data : GPBMessage

@end

#pragma mark - Request11017

typedef GPB_ENUM(Request11017_FieldNumber) {
  Request11017_FieldNumber_Common = 1,
  Request11017_FieldNumber_Params = 2,
};

//关注 取消关注 酒吧    11017
//url: /clubAction/followClub
@interface Request11017 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11017_Params *params;

@end

#pragma mark - Request11017_Params

typedef GPB_ENUM(Request11017_Params_FieldNumber) {
  Request11017_Params_FieldNumber_Flag = 2,
  Request11017_Params_FieldNumber_Clubid = 3,
};

@interface Request11017_Params : GPBMessage

// 1关注    2 取消关注
@property(nonatomic, readwrite) int32_t flag;

//酒吧id
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubid;

@end

#pragma mark - Response11017

typedef GPB_ENUM(Response11017_FieldNumber) {
  Response11017_FieldNumber_Common = 1,
  Response11017_FieldNumber_Data_p = 2,
};

@interface Response11017 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11017_Data *data_p;

@end

#pragma mark - Response11017_Data

@interface Response11017_Data : GPBMessage

@end

#pragma mark - Request11018

typedef GPB_ENUM(Request11018_FieldNumber) {
  Request11018_FieldNumber_Common = 1,
  Request11018_FieldNumber_Params = 2,
};

//获取聊天小组成员列表 11018
//url: /clubAction/getTalkTeamUsers
@interface Request11018 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11018_Params *params;

@end

#pragma mark - Request11018_Params

typedef GPB_ENUM(Request11018_Params_FieldNumber) {
  Request11018_Params_FieldNumber_TalkTeamId = 1,
};

@interface Request11018_Params : GPBMessage

//聊天小组id
@property(nonatomic, readwrite, copy, null_resettable) NSString *talkTeamId;

@end

#pragma mark - Response11018

typedef GPB_ENUM(Response11018_FieldNumber) {
  Response11018_FieldNumber_Common = 1,
  Response11018_FieldNumber_Data_p = 2,
};

@interface Response11018 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11018_Data *data_p;

@end

#pragma mark - Response11018_Data

typedef GPB_ENUM(Response11018_Data_FieldNumber) {
  Response11018_Data_FieldNumber_ChatUsersArray = 1,
};

@interface Response11018_Data : GPBMessage

//聊天成员简要信息
// |chatUsersArray| contains |ChatUser|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *chatUsersArray;
@property(nonatomic, readonly) NSUInteger chatUsersArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
