// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clubinvite.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Request12000_Params;
@class Request12001_Params;
@class Request12002_Params;
@class Request12003_Params;
@class Request12004_Params;
@class Request12005_Params;
@class Request12006_Params;
@class Request12007_Params;
@class Request12008_Params;
@class Request12009_Params;
@class Request12010_Params;
@class Request12011_Params;
@class RequestCommon;
@class Response12000_Data;
@class Response12001_Data;
@class Response12002_Data;
@class Response12003_Data;
@class Response12004_Data;
@class Response12005_Data;
@class Response12006_Data;
@class Response12007_Data;
@class Response12008_Data;
@class Response12009_Data;
@class Response12010_Data;
@class Response12011_Data;
@class ResponseCommon;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ClubinviteRoot

@interface ClubinviteRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Request12000

typedef GPB_ENUM(Request12000_FieldNumber) {
  Request12000_FieldNumber_Common = 1,
  Request12000_FieldNumber_Params = 2,
};

// 创建邀约
//url: /inviteAction/createInvite
@interface Request12000 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12000_Params *params;

@end

#pragma mark - Request12000_Params

typedef GPB_ENUM(Request12000_Params_FieldNumber) {
  Request12000_Params_FieldNumber_HasMoney = 1,
  Request12000_Params_FieldNumber_Money = 2,
  Request12000_Params_FieldNumber_DuringTime = 3,
  Request12000_Params_FieldNumber_DateTime = 4,
  Request12000_Params_FieldNumber_ClubId = 5,
  Request12000_Params_FieldNumber_JustFemale = 6,
  Request12000_Params_FieldNumber_InviteDescription = 7,
  Request12000_Params_FieldNumber_InvitePicArray = 8,
  Request12000_Params_FieldNumber_Latitude = 9,
  Request12000_Params_FieldNumber_Longitude = 10,
  Request12000_Params_FieldNumber_ClubName = 11,
  Request12000_Params_FieldNumber_PayWay = 12,
};

@interface Request12000_Params : GPBMessage

//是否是红包邀约   1，没钱   2 有钱
@property(nonatomic, readwrite) int32_t hasMoney;

//金额数 可选
@property(nonatomic, readwrite) int32_t money;

//约会时长(分钟)  可选
@property(nonatomic, readwrite) int32_t duringTime;

//约会开始 时间戳
@property(nonatomic, readwrite) int32_t dateTime;

//酒吧id
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

//仅限女生 1，仅限女生  2，不仅限女生
@property(nonatomic, readwrite) int32_t justFemale;

//派对描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteDescription;

//派对描述的图片
// |invitePicArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *invitePicArray;
@property(nonatomic, readonly) NSUInteger invitePicArray_Count;

//创建邀约人所在的纬度
@property(nonatomic, readwrite) float latitude;

//创建邀约人所在的经度
@property(nonatomic, readwrite) float longitude;

//酒吧名
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubName;

//支付方式 1AA制 2我请客 3男生请客 4待定   ！
@property(nonatomic, readwrite) int32_t payWay;

@end

#pragma mark - Response12000

typedef GPB_ENUM(Response12000_FieldNumber) {
  Response12000_FieldNumber_Common = 1,
  Response12000_FieldNumber_Data_p = 2,
};

@interface Response12000 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12000_Data *data_p;

@end

#pragma mark - Response12000_Data

@interface Response12000_Data : GPBMessage

@end

#pragma mark - Request12001

typedef GPB_ENUM(Request12001_FieldNumber) {
  Request12001_FieldNumber_Common = 1,
  Request12001_FieldNumber_Params = 2,
};

//查看所有邀约   如果是来自前端的请求，后台算法默认使用我附近的邀约  12001
//url: /inviteAction/getInvites
@interface Request12001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12001_Params *params;

@end

#pragma mark - Request12001_Params

typedef GPB_ENUM(Request12001_Params_FieldNumber) {
  Request12001_Params_FieldNumber_Latitude = 1,
  Request12001_Params_FieldNumber_Longitude = 2,
};

@interface Request12001_Params : GPBMessage

//该人所在的纬度
@property(nonatomic, readwrite) float latitude;

//该人所在的经度
@property(nonatomic, readwrite) float longitude;

@end

#pragma mark - Response12001

typedef GPB_ENUM(Response12001_FieldNumber) {
  Response12001_FieldNumber_Common = 1,
  Response12001_FieldNumber_Data_p = 2,
};

@interface Response12001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12001_Data *data_p;

@end

#pragma mark - Response12001_Data

typedef GPB_ENUM(Response12001_Data_FieldNumber) {
  Response12001_Data_FieldNumber_InvitesArray = 1,
};

@interface Response12001_Data : GPBMessage

//首页显示的邀约的列表信息
// |invitesArray| contains |ClubInvite|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *invitesArray;
@property(nonatomic, readonly) NSUInteger invitesArray_Count;

@end

#pragma mark - Request12002

typedef GPB_ENUM(Request12002_FieldNumber) {
  Request12002_FieldNumber_Common = 1,
  Request12002_FieldNumber_Params = 2,
};

//获取邀约报名人员   12002
//url: /inviteAction/getInviteSignUpUsers
@interface Request12002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12002_Params *params;

@end

#pragma mark - Request12002_Params

typedef GPB_ENUM(Request12002_Params_FieldNumber) {
  Request12002_Params_FieldNumber_InviteId = 1,
};

@interface Request12002_Params : GPBMessage

//邀约id
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteId;

@end

#pragma mark - Response12002

typedef GPB_ENUM(Response12002_FieldNumber) {
  Response12002_FieldNumber_Common = 1,
  Response12002_FieldNumber_Data_p = 2,
};

@interface Response12002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12002_Data *data_p;

@end

#pragma mark - Response12002_Data

typedef GPB_ENUM(Response12002_Data_FieldNumber) {
  Response12002_Data_FieldNumber_InviteUsersArray = 1,
};

@interface Response12002_Data : GPBMessage

//报名了该邀约的所有人员
// |inviteUsersArray| contains |BriefUserInInvite|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *inviteUsersArray;
@property(nonatomic, readonly) NSUInteger inviteUsersArray_Count;

@end

#pragma mark - Request12003

typedef GPB_ENUM(Request12003_FieldNumber) {
  Request12003_FieldNumber_Common = 1,
  Request12003_FieldNumber_Params = 2,
};

//挑选邀约报名人   主体选一个人陪酒啦    12003
//url: /inviteAction/selectSignUpUsers
@interface Request12003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12003_Params *params;

@end

#pragma mark - Request12003_Params

typedef GPB_ENUM(Request12003_Params_FieldNumber) {
  Request12003_Params_FieldNumber_InviteId = 1,
  Request12003_Params_FieldNumber_ChoosedUserid = 2,
};

@interface Request12003_Params : GPBMessage

//邀约的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteId;

//选择的人的userid
@property(nonatomic, readwrite, copy, null_resettable) NSString *choosedUserid;

@end

#pragma mark - Response12003

typedef GPB_ENUM(Response12003_FieldNumber) {
  Response12003_FieldNumber_Common = 1,
  Response12003_FieldNumber_Data_p = 2,
};

@interface Response12003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12003_Data *data_p;

@end

#pragma mark - Response12003_Data

@interface Response12003_Data : GPBMessage

@end

#pragma mark - Request12004

typedef GPB_ENUM(Request12004_FieldNumber) {
  Request12004_FieldNumber_Common = 1,
  Request12004_FieldNumber_Params = 2,
};

//到别人的个人主页后 点击举报按钮的事件   12004
//url: /inviteAction/reportUser
@interface Request12004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12004_Params *params;

@end

#pragma mark - Request12004_Params

typedef GPB_ENUM(Request12004_Params_FieldNumber) {
  Request12004_Params_FieldNumber_UserIdReported = 1,
  Request12004_Params_FieldNumber_Content = 2,
};

@interface Request12004_Params : GPBMessage

//被举报的人的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *userIdReported;

//填写的举报内容
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - Response12004

typedef GPB_ENUM(Response12004_FieldNumber) {
  Response12004_FieldNumber_Common = 1,
  Response12004_FieldNumber_Data_p = 2,
};

@interface Response12004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12004_Data *data_p;

@end

#pragma mark - Response12004_Data

@interface Response12004_Data : GPBMessage

@end

#pragma mark - Request12005

typedef GPB_ENUM(Request12005_FieldNumber) {
  Request12005_FieldNumber_Common = 1,
  Request12005_FieldNumber_Params = 2,
};

//关注别人   12005
//url: /inviteAction/followUser
@interface Request12005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12005_Params *params;

@end

#pragma mark - Request12005_Params

typedef GPB_ENUM(Request12005_Params_FieldNumber) {
  Request12005_Params_FieldNumber_FollowId = 1,
  Request12005_Params_FieldNumber_Flag = 2,
};

@interface Request12005_Params : GPBMessage

//被关注人的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *followId;

//1 关注    2 取消关注
@property(nonatomic, readwrite) int32_t flag;

@end

#pragma mark - Response12005

typedef GPB_ENUM(Response12005_FieldNumber) {
  Response12005_FieldNumber_Common = 1,
  Response12005_FieldNumber_Data_p = 2,
};

@interface Response12005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12005_Data *data_p;

@end

#pragma mark - Response12005_Data

@interface Response12005_Data : GPBMessage

@end

#pragma mark - Request12006

typedef GPB_ENUM(Request12006_FieldNumber) {
  Request12006_FieldNumber_Common = 1,
  Request12006_FieldNumber_Params = 2,
};

//举报邀约  12006
//url: /inviteAction/reportInvite
@interface Request12006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12006_Params *params;

@end

#pragma mark - Request12006_Params

typedef GPB_ENUM(Request12006_Params_FieldNumber) {
  Request12006_Params_FieldNumber_InviteId = 1,
  Request12006_Params_FieldNumber_Reason = 2,
};

@interface Request12006_Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteId;

//举报的理由
@property(nonatomic, readwrite, copy, null_resettable) NSString *reason;

@end

#pragma mark - Response12006

typedef GPB_ENUM(Response12006_FieldNumber) {
  Response12006_FieldNumber_Common = 1,
  Response12006_FieldNumber_Data_p = 2,
};

@interface Response12006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12006_Data *data_p;

@end

#pragma mark - Response12006_Data

@interface Response12006_Data : GPBMessage

@end

#pragma mark - Request12007

typedef GPB_ENUM(Request12007_FieldNumber) {
  Request12007_FieldNumber_Common = 1,
  Request12007_FieldNumber_Params = 2,
};

//收藏邀约  ?  12007                 废弃！！！！！             ？？？
//url: /inviteAction/collectInvite
@interface Request12007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12007_Params *params;

@end

#pragma mark - Request12007_Params

typedef GPB_ENUM(Request12007_Params_FieldNumber) {
  Request12007_Params_FieldNumber_InviteId = 1,
};

@interface Request12007_Params : GPBMessage

//这个地方询问苏丹   ： 不是只能收藏文字和图片吗  怎么收藏邀约了、！！！
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteId;

@end

#pragma mark - Response12007

typedef GPB_ENUM(Response12007_FieldNumber) {
  Response12007_FieldNumber_Common = 1,
  Response12007_FieldNumber_Data_p = 2,
};

@interface Response12007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12007_Data *data_p;

@end

#pragma mark - Response12007_Data

@interface Response12007_Data : GPBMessage

@end

#pragma mark - Request12008

typedef GPB_ENUM(Request12008_FieldNumber) {
  Request12008_FieldNumber_Common = 1,
  Request12008_FieldNumber_Params = 2,
};

//报名邀约 12008
//url: /inviteAction/signUpInvite
@interface Request12008 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12008_Params *params;

@end

#pragma mark - Request12008_Params

typedef GPB_ENUM(Request12008_Params_FieldNumber) {
  Request12008_Params_FieldNumber_InviteId = 1,
};

@interface Request12008_Params : GPBMessage

//报名的邀约的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteId;

@end

#pragma mark - Response12008

typedef GPB_ENUM(Response12008_FieldNumber) {
  Response12008_FieldNumber_Common = 1,
  Response12008_FieldNumber_Data_p = 2,
};

@interface Response12008 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12008_Data *data_p;

@end

#pragma mark - Response12008_Data

@interface Response12008_Data : GPBMessage

@end

#pragma mark - Request12009

typedef GPB_ENUM(Request12009_FieldNumber) {
  Request12009_FieldNumber_Common = 1,
  Request12009_FieldNumber_Params = 2,
};

//邀约选择酒吧时 获取酒吧列表  12009
//url: /inviteAction/getInviteClubs
@interface Request12009 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12009_Params *params;

@end

#pragma mark - Request12009_Params

typedef GPB_ENUM(Request12009_Params_FieldNumber) {
  Request12009_Params_FieldNumber_Latitude = 1,
  Request12009_Params_FieldNumber_Longitude = 2,
  Request12009_Params_FieldNumber_Keyword = 3,
};

@interface Request12009_Params : GPBMessage

//用户当前的纬度
@property(nonatomic, readwrite) float latitude;

//用户当前的经度
@property(nonatomic, readwrite) float longitude;

//可选字段  搜索的keyword
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

@end

#pragma mark - Response12009

typedef GPB_ENUM(Response12009_FieldNumber) {
  Response12009_FieldNumber_Common = 1,
  Response12009_FieldNumber_Data_p = 2,
};

@interface Response12009 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12009_Data *data_p;

@end

#pragma mark - Response12009_Data

typedef GPB_ENUM(Response12009_Data_FieldNumber) {
  Response12009_Data_FieldNumber_InviteClubsArray = 1,
};

@interface Response12009_Data : GPBMessage

//邀约酒吧的简要信息
// |inviteClubsArray| contains |BriefInviteClub|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *inviteClubsArray;
@property(nonatomic, readonly) NSUInteger inviteClubsArray_Count;

@end

#pragma mark - Request12010

typedef GPB_ENUM(Request12010_FieldNumber) {
  Request12010_FieldNumber_Common = 1,
  Request12010_FieldNumber_Params = 2,
};

//给客体评分 12010
//url: /inviteAction/score
@interface Request12010 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12010_Params *params;

@end

#pragma mark - Request12010_Params

typedef GPB_ENUM(Request12010_Params_FieldNumber) {
  Request12010_Params_FieldNumber_Inviteid = 1,
  Request12010_Params_FieldNumber_JudgeId = 2,
  Request12010_Params_FieldNumber_Score = 3,
  Request12010_Params_FieldNumber_Content = 4,
};

@interface Request12010_Params : GPBMessage

//邀约的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteid;

//被评价人的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *judgeId;

//评分
@property(nonatomic, readwrite) int32_t score;

//评分的文字选择描述，每条描述用“，”中文逗号分开 ，构造出字符串
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - Response12010

typedef GPB_ENUM(Response12010_FieldNumber) {
  Response12010_FieldNumber_Common = 1,
  Response12010_FieldNumber_Data_p = 2,
};

@interface Response12010 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12010_Data *data_p;

@end

#pragma mark - Response12010_Data

@interface Response12010_Data : GPBMessage

@end

#pragma mark - Request12011

typedef GPB_ENUM(Request12011_FieldNumber) {
  Request12011_FieldNumber_Common = 1,
  Request12011_FieldNumber_Params = 2,
};

//完成邀约 12011
//url: /inviteAction/doneInvite
@interface Request12011 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12011_Params *params;

@end

#pragma mark - Request12011_Params

typedef GPB_ENUM(Request12011_Params_FieldNumber) {
  Request12011_Params_FieldNumber_Inviteid = 1,
  Request12011_Params_FieldNumber_ProgressTime = 2,
};

@interface Request12011_Params : GPBMessage

//邀约的id
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteid;

//约会进行的时间（！不是约会的duringtime  而是用户实际约会的时间  <= duringTime） 单位： 分钟
@property(nonatomic, readwrite) int32_t progressTime;

@end

#pragma mark - Response12011

typedef GPB_ENUM(Response12011_FieldNumber) {
  Response12011_FieldNumber_Common = 1,
  Response12011_FieldNumber_Data_p = 2,
};

@interface Response12011 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12011_Data *data_p;

@end

#pragma mark - Response12011_Data

@interface Response12011_Data : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
