// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class BriefUser;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CommonRoot

@interface CommonRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - RequestCommon

typedef GPB_ENUM(RequestCommon_FieldNumber) {
  RequestCommon_FieldNumber_Userid = 1,
  RequestCommon_FieldNumber_Userkey = 2,
  RequestCommon_FieldNumber_Cmdid = 3,
  RequestCommon_FieldNumber_Timestamp = 4,
  RequestCommon_FieldNumber_Version = 5,
  RequestCommon_FieldNumber_Platform = 6,
};

///////////////////////////////////   请求和返回中包含的common        /////////////////////
@interface RequestCommon : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userkey;

@property(nonatomic, readwrite) int32_t cmdid;

@property(nonatomic, readwrite) int64_t timestamp;

// 版本, 1.0.0a
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

// 1-Android, 2-iOS
@property(nonatomic, readwrite) int32_t platform;

@end

#pragma mark - ResponseCommon

typedef GPB_ENUM(ResponseCommon_FieldNumber) {
  ResponseCommon_FieldNumber_Code = 1,
  ResponseCommon_FieldNumber_Message = 2,
  ResponseCommon_FieldNumber_Cmdid = 3,
  ResponseCommon_FieldNumber_Timestamp = 4,
  ResponseCommon_FieldNumber_Userid = 5,
};

@interface ResponseCommon : GPBMessage

//状态码   0：正常  其他数值表示有错误
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite) int32_t cmdid;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userid;

@end

#pragma mark - ClubFile

typedef GPB_ENUM(ClubFile_FieldNumber) {
  ClubFile_FieldNumber_Id_p = 1,
  ClubFile_FieldNumber_Filename = 2,
  ClubFile_FieldNumber_URL = 3,
  ClubFile_FieldNumber_Content = 4,
  ClubFile_FieldNumber_Mimetype = 5,
};

// 通用类
@interface ClubFile : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *filename;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uRL;

@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mimetype;

@end

#pragma mark - BriefUser

typedef GPB_ENUM(BriefUser_FieldNumber) {
  BriefUser_FieldNumber_Userid = 1,
  BriefUser_FieldNumber_Username = 2,
  BriefUser_FieldNumber_Sex = 3,
  BriefUser_FieldNumber_Age = 4,
  BriefUser_FieldNumber_Job = 5,
  BriefUser_FieldNumber_State = 6,
  BriefUser_FieldNumber_Signature = 7,
  BriefUser_FieldNumber_Avatar = 8,
  BriefUser_FieldNumber_ClubNumber = 9,
};

//用户简要信息
@interface BriefUser : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

// 1:男的   2:女的
@property(nonatomic, readwrite) int32_t sex;

@property(nonatomic, readwrite) int32_t age;

@property(nonatomic, readwrite, copy, null_resettable) NSString *job;

//用户身份状态   暂定 0：普通用户  1：vip1用户  2：vip2用户
@property(nonatomic, readwrite) int32_t state;

//个性签名
@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

//用户头像
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

//club号
@property(nonatomic, readwrite) int64_t clubNumber;

@end

#pragma mark - BriefUserInInvite

typedef GPB_ENUM(BriefUserInInvite_FieldNumber) {
  BriefUserInInvite_FieldNumber_BriefUser = 1,
  BriefUserInInvite_FieldNumber_SignupState = 2,
};

//报名邀约的人员
@interface BriefUserInInvite : GPBMessage

//用户简要信息
@property(nonatomic, readwrite) BOOL hasBriefUser;
@property(nonatomic, readwrite, strong, null_resettable) BriefUser *briefUser;

//报名状态  报名状态0，被选中1，没有选中2，
@property(nonatomic, readwrite) int32_t signupState;

@end

#pragma mark - UserAvatarAndName

typedef GPB_ENUM(UserAvatarAndName_FieldNumber) {
  UserAvatarAndName_FieldNumber_Userid = 1,
  UserAvatarAndName_FieldNumber_Avatar = 2,
  UserAvatarAndName_FieldNumber_Username = 3,
};

@interface UserAvatarAndName : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@end

#pragma mark - ChatUser

typedef GPB_ENUM(ChatUser_FieldNumber) {
  ChatUser_FieldNumber_Userid = 1,
  ChatUser_FieldNumber_Avatar = 2,
  ChatUser_FieldNumber_Username = 4,
  ChatUser_FieldNumber_State = 5,
};

@interface ChatUser : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

// 1:活跃成员   2：不咋活跃
@property(nonatomic, readwrite) int32_t state;

@end

#pragma mark - ClubInvite

typedef GPB_ENUM(ClubInvite_FieldNumber) {
  ClubInvite_FieldNumber_BriefUser = 1,
  ClubInvite_FieldNumber_CreateTime = 2,
  ClubInvite_FieldNumber_CreateLocation = 3,
  ClubInvite_FieldNumber_InviteLocation = 4,
  ClubInvite_FieldNumber_StartTime = 5,
  ClubInvite_FieldNumber_EndTime = 6,
  ClubInvite_FieldNumber_During = 7,
  ClubInvite_FieldNumber_Description_p = 8,
  ClubInvite_FieldNumber_InvitePicArray = 9,
  ClubInvite_FieldNumber_HasMoney = 10,
  ClubInvite_FieldNumber_PayWay = 11,
  ClubInvite_FieldNumber_PayMoney = 12,
  ClubInvite_FieldNumber_InviteState = 13,
  ClubInvite_FieldNumber_MyState = 14,
  ClubInvite_FieldNumber_CreateLocationLatitude = 15,
  ClubInvite_FieldNumber_CreateLocationLongitude = 16,
  ClubInvite_FieldNumber_InviteLocationLatitude = 17,
  ClubInvite_FieldNumber_InviteLocationLongitude = 18,
  ClubInvite_FieldNumber_SignUpCount = 19,
  ClubInvite_FieldNumber_InviteId = 20,
  ClubInvite_FieldNumber_JustFemale = 21,
};

//邀约
@interface ClubInvite : GPBMessage

//邀约发起人
@property(nonatomic, readwrite) BOOL hasBriefUser;
@property(nonatomic, readwrite, strong, null_resettable) BriefUser *briefUser;

//发起时间
@property(nonatomic, readwrite) int64_t createTime;

//发起邀约的地址   待定弃用！！！！！
@property(nonatomic, readwrite, copy, null_resettable) NSString *createLocation;

//邀约活动的地址  酒吧名
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteLocation;

//开始时间戳
@property(nonatomic, readwrite) int64_t startTime;

//结束时间       (使用开始时间戳+during*60*1000)
@property(nonatomic, readwrite) int64_t endTime;

//持续时间  分钟
@property(nonatomic, readwrite) int32_t during;

//派对描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

//邀约描述添加的图片
// |invitePicArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *invitePicArray;
@property(nonatomic, readonly) NSUInteger invitePicArray_Count;

//是否是金钱邀约  1：不是 2：是
@property(nonatomic, readwrite) int32_t hasMoney;

//支付方式    1:app内的虚拟货币   2:微信支付     3：支付宝
@property(nonatomic, readwrite) int32_t payWay;

//支付金额
@property(nonatomic, readwrite) int32_t payMoney;

//邀约的状态  发起中0，已选人1，确认到达2，已完成3 
@property(nonatomic, readwrite) int32_t inviteState;

//该邀约中我（非发起人）的状态 未报名0， 已报名1， 已被选中2， 未被选中3
@property(nonatomic, readwrite) int32_t myState;

//创建邀约的纬度
@property(nonatomic, readwrite) float createLocationLatitude;

//创建邀约的经度
@property(nonatomic, readwrite) float createLocationLongitude;

//邀约酒吧的纬度
@property(nonatomic, readwrite) float inviteLocationLatitude;

//邀约酒吧的经度
@property(nonatomic, readwrite) float inviteLocationLongitude;

//邀约报名的人数
@property(nonatomic, readwrite) int32_t signUpCount;

//邀约id
@property(nonatomic, readwrite, copy, null_resettable) NSString *inviteId;

//仅限女性   1：仅限女生  2：不仅限女生
@property(nonatomic, readwrite) int32_t justFemale;

@end

#pragma mark - BriefClub

typedef GPB_ENUM(BriefClub_FieldNumber) {
  BriefClub_FieldNumber_Clubid = 1,
  BriefClub_FieldNumber_Clubname = 2,
  BriefClub_FieldNumber_ClubAvatar = 3,
  BriefClub_FieldNumber_ClubLocation = 4,
  BriefClub_FieldNumber_ClubDistance = 5,
  BriefClub_FieldNumber_FollowState = 6,
  BriefClub_FieldNumber_MaleCount = 7,
  BriefClub_FieldNumber_FamaleCount = 8,
  BriefClub_FieldNumber_ClubLatitude = 9,
  BriefClub_FieldNumber_ClubLongitude = 10,
  BriefClub_FieldNumber_LivePhotosArray = 11,
};

//酒吧简要信息
@interface BriefClub : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubname;

//酒吧显示的“头像”
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubAvatar;

//酒吧具体位置
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubLocation;

//酒吧距离我多远
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubDistance;

// 未关注0, 已关注1
@property(nonatomic, readwrite) int32_t followState;

//人数 酒吧聊天室 男
@property(nonatomic, readwrite) int32_t maleCount;

//人数 酒吧聊天室 女
@property(nonatomic, readwrite) int32_t famaleCount;

//酒吧的纬度
@property(nonatomic, readwrite) float clubLatitude;

//酒吧的经度
@property(nonatomic, readwrite) float clubLongitude;

//酒吧的livephotos   获取我关注的酒吧没有传这个内容
// |livePhotosArray| contains |LivePhoto|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *livePhotosArray;
@property(nonatomic, readonly) NSUInteger livePhotosArray_Count;

@end

#pragma mark - BriefInviteClub

typedef GPB_ENUM(BriefInviteClub_FieldNumber) {
  BriefInviteClub_FieldNumber_Clubid = 1,
  BriefInviteClub_FieldNumber_Clubname = 2,
  BriefInviteClub_FieldNumber_ClubLocation = 3,
};

//邀约搜索的酒吧 得到的酒吧简要信息
@interface BriefInviteClub : GPBMessage

//酒吧id
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubid;

//酒吧名
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubname;

//酒吧位置 文字描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *clubLocation;

@end

#pragma mark - UserAvatar

typedef GPB_ENUM(UserAvatar_FieldNumber) {
  UserAvatar_FieldNumber_AvatarId = 1,
  UserAvatar_FieldNumber_URL = 2,
  UserAvatar_FieldNumber_Order = 3,
};

@interface UserAvatar : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uRL;

//头像的顺序
@property(nonatomic, readwrite) int32_t order;

@end

#pragma mark - BindApp

typedef GPB_ENUM(BindApp_FieldNumber) {
  BindApp_FieldNumber_Bindid = 1,
  BindApp_FieldNumber_AppName = 2,
  BindApp_FieldNumber_AppUsername = 3,
  BindApp_FieldNumber_AppPsw = 4,
  BindApp_FieldNumber_AddTime = 5,
};

@interface BindApp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *bindid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appUsername;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appPsw;

@property(nonatomic, readwrite) int64_t addTime;

@end

#pragma mark - DetailUser

typedef GPB_ENUM(DetailUser_FieldNumber) {
  DetailUser_FieldNumber_Userid = 1,
  DetailUser_FieldNumber_Username = 2,
  DetailUser_FieldNumber_UserAvatarArray = 3,
  DetailUser_FieldNumber_Sex = 4,
  DetailUser_FieldNumber_Birthday = 5,
  DetailUser_FieldNumber_Constellation = 6,
  DetailUser_FieldNumber_LastLocation = 7,
  DetailUser_FieldNumber_LastTime = 8,
  DetailUser_FieldNumber_Signature = 9,
  DetailUser_FieldNumber_EmotionState = 10,
  DetailUser_FieldNumber_Job = 11,
  DetailUser_FieldNumber_School = 12,
  DetailUser_FieldNumber_Hometown = 13,
  DetailUser_FieldNumber_VclubNumber = 14,
  DetailUser_FieldNumber_Movie = 15,
  DetailUser_FieldNumber_Music = 16,
  DetailUser_FieldNumber_WorkLocation = 17,
  DetailUser_FieldNumber_ActiveLocation = 18,
  DetailUser_FieldNumber_Relationship = 19,
  DetailUser_FieldNumber_RegisteTime = 20,
  DetailUser_FieldNumber_BackgroundURL = 21,
  DetailUser_FieldNumber_BindAppsArray = 22,
  DetailUser_FieldNumber_AccountSafe = 23,
  DetailUser_FieldNumber_DataIntegrity = 24,
  DetailUser_FieldNumber_Hobby = 25,
  DetailUser_FieldNumber_SelfIntro = 26,
};

@interface DetailUser : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

//头像数组
// |userAvatarArray| contains |UserAvatar|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *userAvatarArray;
@property(nonatomic, readonly) NSUInteger userAvatarArray_Count;

@property(nonatomic, readwrite) int32_t sex;

//生日
@property(nonatomic, readwrite, copy, null_resettable) NSString *birthday;

//星座
@property(nonatomic, readwrite) int32_t constellation;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastLocation;

@property(nonatomic, readwrite) int64_t lastTime;

//签名
@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

//情感状态     1单身  2热恋 3已婚 4 离异
@property(nonatomic, readwrite) int32_t emotionState;

//职业
@property(nonatomic, readwrite, copy, null_resettable) NSString *job;

//学校
@property(nonatomic, readwrite, copy, null_resettable) NSString *school;

//家乡
@property(nonatomic, readwrite, copy, null_resettable) NSString *hometown;

//vclub号
@property(nonatomic, readwrite) int64_t vclubNumber;

//喜欢的电影
@property(nonatomic, readwrite, copy, null_resettable) NSString *movie;

//喜欢的音乐
@property(nonatomic, readwrite, copy, null_resettable) NSString *music;

//工作地点
@property(nonatomic, readwrite, copy, null_resettable) NSString *workLocation;

//常出没地
@property(nonatomic, readwrite, copy, null_resettable) NSString *activeLocation;

//关系？
@property(nonatomic, readwrite, copy, null_resettable) NSString *relationship;

//注册时间
@property(nonatomic, readwrite) int64_t registeTime;

//用户背景url
@property(nonatomic, readwrite, copy, null_resettable) NSString *backgroundURL;

//绑定的app
// |bindAppsArray| contains |BindApp|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *bindAppsArray;
@property(nonatomic, readonly) NSUInteger bindAppsArray_Count;

//账号安全等级   1,2,3  低 中 高
@property(nonatomic, readwrite) int32_t accountSafe;

//资料完整度          例如：50 表示50%
@property(nonatomic, readwrite) int32_t dataIntegrity;

//兴趣爱好
@property(nonatomic, readwrite, copy, null_resettable) NSString *hobby;

//个人说明
@property(nonatomic, readwrite, copy, null_resettable) NSString *selfIntro;

@end

#pragma mark - ClubActivityBrief

typedef GPB_ENUM(ClubActivityBrief_FieldNumber) {
  ClubActivityBrief_FieldNumber_ActivityId = 1,
  ClubActivityBrief_FieldNumber_ClubId = 2,
  ClubActivityBrief_FieldNumber_ActivityURL = 3,
};

//酒吧活动  简短
@interface ClubActivityBrief : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *activityId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *activityURL;

@end

#pragma mark - LivePhoto

typedef GPB_ENUM(LivePhoto_FieldNumber) {
  LivePhoto_FieldNumber_ClubId = 1,
  LivePhoto_FieldNumber_UserId = 2,
  LivePhoto_FieldNumber_Thumbnail = 3,
  LivePhoto_FieldNumber_BigPicture = 4,
  LivePhoto_FieldNumber_BrowserCount = 5,
  LivePhoto_FieldNumber_LikeCount = 6,
  LivePhoto_FieldNumber_LikeState = 7,
};

//livephoto
@interface LivePhoto : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

//缩略图url
@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnail;

//大图的url
@property(nonatomic, readwrite, copy, null_resettable) NSString *bigPicture;

//浏览量
@property(nonatomic, readwrite) int32_t browserCount;

//点赞量
@property(nonatomic, readwrite) int32_t likeCount;

//自己是否已经点赞  1,点了  2， 没点
@property(nonatomic, readwrite) int32_t likeState;

@end

#pragma mark - ClubDetail

typedef GPB_ENUM(ClubDetail_FieldNumber) {
  ClubDetail_FieldNumber_ClubId = 1,
  ClubDetail_FieldNumber_ClubName = 2,
  ClubDetail_FieldNumber_ClubCover = 3,
  ClubDetail_FieldNumber_ClubDescription = 4,
  ClubDetail_FieldNumber_ClubLocation = 5,
  ClubDetail_FieldNumber_ClubPhone = 6,
  ClubDetail_FieldNumber_BrowserCount = 7,
  ClubDetail_FieldNumber_LikeCount = 8,
  ClubDetail_FieldNumber_ClubActivitysArray = 9,
  ClubDetail_FieldNumber_LivePhotoArray = 10,
  ClubDetail_FieldNumber_LikeState = 11,
  ClubDetail_FieldNumber_SignupState = 12,
};

//酒吧详情
@interface ClubDetail : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubCover;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubDescription;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubLocation;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clubPhone;

@property(nonatomic, readwrite) int32_t browserCount;

@property(nonatomic, readwrite) int32_t likeCount;

// |clubActivitysArray| contains |ClubActivityBrief|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *clubActivitysArray;
@property(nonatomic, readonly) NSUInteger clubActivitysArray_Count;

//酒吧的livephoto
// |livePhotoArray| contains |LivePhoto|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *livePhotoArray;
@property(nonatomic, readonly) NSUInteger livePhotoArray_Count;

//自己是否已经点赞  1.点了 2， 没点
@property(nonatomic, readwrite) int32_t likeState;

//酒吧签到情况 1已经签到  2：未签到
@property(nonatomic, readwrite) int32_t signupState;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
